// Generated by scripts/generate-component-previews.mjs — do not edit by hand.
// Maps a component file (relative to src/components) to its *.preview.tsx module.

import type { ComponentPreviewModule } from "@/lib/component-preview";
import * as preview0 from "@/components/CopyCommand.preview";
import * as preview1 from "@/components/CopyEmailButton.preview";
import * as preview2 from "@/components/animation/AnimatedGradient.preview";
import * as preview3 from "@/components/animation/FloatingElement.preview";
import * as preview4 from "@/components/animation/MagneticButton.preview";
import * as preview5 from "@/components/animation/ScrollReveal.preview";
import * as preview6 from "@/components/animation/SpotlightCard.preview";
import * as preview7 from "@/components/animation/TiltCard.preview";
import * as preview8 from "@/components/blog/BlogCard.preview";
import * as preview9 from "@/components/blog/BlogList.preview";
import * as preview10 from "@/components/contact/BookingButton.preview";
import * as preview11 from "@/components/contact/ContactForm.preview";
import * as preview12 from "@/components/content/MarkdownRenderer.preview";
import * as preview13 from "@/components/icons/BrandIcons.preview";
import * as preview14 from "@/components/layout/Footer.preview";
import * as preview15 from "@/components/layout/Navbar.preview";
import * as preview16 from "@/components/layout/Section.preview";
import * as preview17 from "@/components/mnemo/Architecture.preview";
import * as preview18 from "@/components/mnemo/AuthShowcase.preview";
import * as preview19 from "@/components/mnemo/ChatShowcase.preview";
import * as preview20 from "@/components/mnemo/CtaSection.preview";
import * as preview21 from "@/components/mnemo/DashboardShowcase.preview";
import * as preview22 from "@/components/mnemo/DevelopmentJourney.preview";
import * as preview23 from "@/components/mnemo/FeaturesBento.preview";
import * as preview24 from "@/components/mnemo/HowItWorks.preview";
import * as preview25 from "@/components/mnemo/MnemoHero.preview";
import * as preview26 from "@/components/mnemo/MnemoLogo.preview";
import * as preview27 from "@/components/mnemo/PerformanceMetrics.preview";
import * as preview28 from "@/components/mnemo/ProblemStatement.preview";
import * as preview29 from "@/components/mnemo/QuizShowcase.preview";
import * as preview30 from "@/components/mnemo/Roadmap.preview";
import * as preview31 from "@/components/mnemo/ScreenshotsGallery.preview";
import * as preview32 from "@/components/mnemo/TechStack.preview";
import * as preview33 from "@/components/mnemo/VideoShowcase.preview";
import * as preview34 from "@/components/mnemo/WhatIsMnemo.preview";
import * as preview35 from "@/components/mnemo/WhyBuilt.preview";
import * as preview36 from "@/components/projects/BuildingList.preview";
import * as preview37 from "@/components/projects/CliTools.preview";
import * as preview38 from "@/components/projects/ExperienceTimeline.preview";
import * as preview39 from "@/components/projects/FeaturedProjectCards.preview";
import * as preview40 from "@/components/projects/ProjectBadges.preview";
import * as preview41 from "@/components/projects/ProjectCard.preview";
import * as preview42 from "@/components/projects/ProjectsList.preview";
import * as preview43 from "@/components/sections/home/BuildingInPublic.preview";
import * as preview44 from "@/components/sections/home/FinalCta.preview";
import * as preview45 from "@/components/sections/home/ForFounders.preview";
import * as preview46 from "@/components/sections/home/Hero.preview";
import * as preview47 from "@/components/sections/home/Packages.preview";
import * as preview48 from "@/components/sections/home/Services.preview";
import * as preview49 from "@/components/sections/home/Stack.preview";
import * as preview50 from "@/components/sections/home/StatsRow.preview";
import * as preview51 from "@/components/sections/home/Work.preview";
import * as preview52 from "@/components/sections/home/Writing.preview";
import * as preview53 from "@/components/ui/avatar.preview";
import * as preview54 from "@/components/ui/badge.preview";
import * as preview55 from "@/components/ui/button.preview";
import * as preview56 from "@/components/ui/card.preview";
import * as preview57 from "@/components/ui/dialog.preview";
import * as preview58 from "@/components/ui/eyebrow.preview";
import * as preview59 from "@/components/ui/input.preview";
import * as preview60 from "@/components/ui/scroll-area.preview";
import * as preview61 from "@/components/ui/select.preview";
import * as preview62 from "@/components/ui/separator.preview";
import * as preview63 from "@/components/ui/sheet.preview";
import * as preview64 from "@/components/ui/skeleton.preview";
import * as preview65 from "@/components/ui/textarea.preview";
import * as preview66 from "@/components/ui/tooltip.preview";

export const componentPreviews: Record<string, ComponentPreviewModule> = {
  "CopyCommand.tsx": preview0,
  "CopyEmailButton.tsx": preview1,
  "animation/AnimatedGradient.tsx": preview2,
  "animation/FloatingElement.tsx": preview3,
  "animation/MagneticButton.tsx": preview4,
  "animation/ScrollReveal.tsx": preview5,
  "animation/SpotlightCard.tsx": preview6,
  "animation/TiltCard.tsx": preview7,
  "blog/BlogCard.tsx": preview8,
  "blog/BlogList.tsx": preview9,
  "contact/BookingButton.tsx": preview10,
  "contact/ContactForm.tsx": preview11,
  "content/MarkdownRenderer.tsx": preview12,
  "icons/BrandIcons.tsx": preview13,
  "layout/Footer.tsx": preview14,
  "layout/Navbar.tsx": preview15,
  "layout/Section.tsx": preview16,
  "mnemo/Architecture.tsx": preview17,
  "mnemo/AuthShowcase.tsx": preview18,
  "mnemo/ChatShowcase.tsx": preview19,
  "mnemo/CtaSection.tsx": preview20,
  "mnemo/DashboardShowcase.tsx": preview21,
  "mnemo/DevelopmentJourney.tsx": preview22,
  "mnemo/FeaturesBento.tsx": preview23,
  "mnemo/HowItWorks.tsx": preview24,
  "mnemo/MnemoHero.tsx": preview25,
  "mnemo/MnemoLogo.tsx": preview26,
  "mnemo/PerformanceMetrics.tsx": preview27,
  "mnemo/ProblemStatement.tsx": preview28,
  "mnemo/QuizShowcase.tsx": preview29,
  "mnemo/Roadmap.tsx": preview30,
  "mnemo/ScreenshotsGallery.tsx": preview31,
  "mnemo/TechStack.tsx": preview32,
  "mnemo/VideoShowcase.tsx": preview33,
  "mnemo/WhatIsMnemo.tsx": preview34,
  "mnemo/WhyBuilt.tsx": preview35,
  "projects/BuildingList.tsx": preview36,
  "projects/CliTools.tsx": preview37,
  "projects/ExperienceTimeline.tsx": preview38,
  "projects/FeaturedProjectCards.tsx": preview39,
  "projects/ProjectBadges.tsx": preview40,
  "projects/ProjectCard.tsx": preview41,
  "projects/ProjectsList.tsx": preview42,
  "sections/home/BuildingInPublic.tsx": preview43,
  "sections/home/FinalCta.tsx": preview44,
  "sections/home/ForFounders.tsx": preview45,
  "sections/home/Hero.tsx": preview46,
  "sections/home/Packages.tsx": preview47,
  "sections/home/Services.tsx": preview48,
  "sections/home/Stack.tsx": preview49,
  "sections/home/StatsRow.tsx": preview50,
  "sections/home/Work.tsx": preview51,
  "sections/home/Writing.tsx": preview52,
  "ui/avatar.tsx": preview53,
  "ui/badge.tsx": preview54,
  "ui/button.tsx": preview55,
  "ui/card.tsx": preview56,
  "ui/dialog.tsx": preview57,
  "ui/eyebrow.tsx": preview58,
  "ui/input.tsx": preview59,
  "ui/scroll-area.tsx": preview60,
  "ui/select.tsx": preview61,
  "ui/separator.tsx": preview62,
  "ui/sheet.tsx": preview63,
  "ui/skeleton.tsx": preview64,
  "ui/textarea.tsx": preview65,
  "ui/tooltip.tsx": preview66,
};
